### ISSUE TITLE
Longest Common Subsequence(LCS)

### ISSUE THREAD

**Issue by sdas2k3** [vaibhavshukla06/Hacktoberfest2023#2]
Heyy @vaibhavshukla06  this is a very famous problem from LeetCode based on Dynamic Programming.
Link : https://leetcode.com/problems/longest-common-subsequence/description/
Kindly assign this to be as a part of Hactoberfest2023.I will be solving this in C++ language.
Thanks

**Comment by ogvaibhavshukla** [comment]
yes go ahead

**Comment by ogvaibhavshukla** [comment]
hey why did you close it, send me a PR again and I will merge it😉

**Comment by ogvaibhavshukla** [comment]
@sdas2k3
